CLIENT_ID = "3182f7bb-73d7-45e0-a6da-98072cb1cfc6"
TENANT_ID = "6525df30-f744-44ad-ab15-7ecfe0024a2a"
CLIENT_SECRET = "nVi8Q~RPMyPGX-6z1RQlU7FpxxUuvUC595NZRbPH"
SHAREPOINT_SITE = "jmsengineering.sharepoint.com"